spring:
  datasource:
    url: jdbc:h2:mem:flashcards
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:flashcards}
    password: ${DB_PASSWORD:flashcards}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
